/**
 * Gate 14 §6-§16: establishes the controlled GCP knowledge taxonomy -
 * GcpDomain records, the Role-to-Domain reference matrix, and the initial
 * LearningObjective library. Every domain/objective/mapping below was
 * designed against the ACTUAL real observation evidence (see
 * `docs/gcp-knowledge-taxonomy-and-curation.md` §2 for the inspection
 * findings that produced this list) and standard GCP training curricula -
 * never generated by an LLM, never fabricated to pad coverage statistics.
 *
 * Idempotent: upserts by stable `code`, safe to re-run.
 *
 * Run with: pnpm --filter @gcp/api taxonomy:seed
 */
import { NestFactory } from '@nestjs/core';

import { LearningObjectiveSourceBasis, UserRole } from '@gcp/shared';

import { AppModule } from '../src/app.module';
import { PrismaService } from '../src/prisma/prisma.service';

const IMPORT_ADMIN_EMAIL = 'data-import-admin@gcp-training.local';

interface DomainSeed {
  code: string;
  name: string;
  description: string;
  sortOrder: number;
}

/** Gate 14 §6/§8/§9: pruned and merged from the prompt's 36-item candidate
 * checklist down to 25 domains that are each independently defensible
 * against either the real observation evidence (Gate 12 dataset) or
 * standard ICH E6 GCP curriculum structure - never split further than the
 * evidence or curriculum actually supports (Gate 14 §3). */
const DOMAINS: DomainSeed[] = [
  {
    code: 'GCP_FUNDAMENTALS',
    name: 'GCP Fundamentals & Principles',
    description:
      'The foundational principles of Good Clinical Practice: subject rights and wellbeing, scientific soundness, and the ethical conduct of clinical research.',
    sortOrder: 10,
  },
  {
    code: 'INVESTIGATOR_RESPONSIBILITIES',
    name: 'Investigator Responsibilities',
    description:
      'The duties of the principal investigator and sub-investigators for the conduct, oversight, and integrity of a clinical trial at their site.',
    sortOrder: 20,
  },
  {
    code: 'SPONSOR_RESPONSIBILITIES',
    name: 'Sponsor Responsibilities',
    description:
      'The duties of a trial sponsor for trial design, oversight, safety monitoring, and quality management across all participating sites.',
    sortOrder: 30,
  },
  {
    code: 'CRO_OVERSIGHT',
    name: 'CRO / Service Provider Oversight',
    description:
      'How a sponsor delegates trial-related duties to a contract research organization or other service provider while retaining ultimate responsibility for trial quality and integrity.',
    sortOrder: 40,
  },
  {
    code: 'PROTOCOL_COMPLIANCE',
    name: 'Protocol Compliance & Deviations',
    description:
      'Adherence to the approved trial protocol and its amendments, including eligibility criteria, and the identification, documentation, and escalation of protocol deviations.',
    sortOrder: 50,
  },
  {
    code: 'INFORMED_CONSENT',
    name: 'Informed Consent',
    description:
      'The process of obtaining and documenting a subject’s voluntary, informed agreement to participate in a trial, including re-consent when the protocol or risk profile changes.',
    sortOrder: 60,
  },
  {
    code: 'ETHICS_OVERSIGHT',
    name: 'Institutional Review / Ethics Committee Oversight',
    description:
      'The role of an Institutional Review Board or Independent Ethics Committee in reviewing, approving, and continuing to oversee a trial to protect subject rights and welfare.',
    sortOrder: 70,
  },
  {
    code: 'SUBJECT_SAFETY',
    name: 'Subject Safety & Adverse Event Reporting',
    description:
      'The identification, documentation, causality assessment, and timely reporting of adverse events and serious adverse events to protect trial subjects.',
    sortOrder: 80,
  },
  {
    code: 'SOURCE_DOCUMENTATION',
    name: 'Source Data / Source Documentation',
    description:
      'The original records and certified copies from which trial data are transcribed, and the practices that keep them accurate, complete, and attributable.',
    sortOrder: 90,
  },
  {
    code: 'ESSENTIAL_DOCUMENTS',
    name: 'Essential Documents / Trial Master File',
    description:
      'The documents that individually and collectively permit evaluation of trial conduct and data quality, organized in the Trial Master File and Investigator Site File.',
    sortOrder: 100,
  },
  {
    code: 'MONITORING_QUALITY',
    name: 'Monitoring & Risk-Based Quality Management',
    description:
      'The sponsor’s oversight of trial conduct through monitoring visits and a risk-based approach that focuses resources on the areas most likely to affect subject safety and data reliability.',
    sortOrder: 110,
  },
  {
    code: 'DATA_INTEGRITY',
    name: 'Data Integrity',
    description:
      'Practices that keep clinical, laboratory, and computerized-system data attributable, legible, contemporaneous, original, and accurate (ALCOA+) throughout their lifecycle.',
    sortOrder: 120,
  },
  {
    code: 'CLINICAL_DATA_MANAGEMENT',
    name: 'Clinical Data Management',
    description:
      'The collection, cleaning, and management of clinical trial data through case report forms and electronic data capture systems.',
    sortOrder: 130,
  },
  {
    code: 'BIOANALYTICAL_OPERATIONS',
    name: 'Laboratory / Bioanalytical Operations',
    description:
      'The generation, review, and reporting of bioanalytical and laboratory data, including method validation, raw-data integrity, and instrument qualification.',
    sortOrder: 140,
  },
  {
    code: 'INVESTIGATIONAL_PRODUCT',
    name: 'Investigational Product Management, Randomization & Blinding',
    description:
      'The accountability, storage, dispensing, and reconciliation of investigational product, and the procedures that maintain randomization integrity and treatment blinding.',
    sortOrder: 150,
  },
  {
    code: 'COMPUTERIZED_SYSTEMS',
    name: 'Computerized Systems & Electronic Records',
    description:
      'The use of computerized systems (EDC, eCOA, LIMS, and similar) to create, modify, or maintain trial records, and the controls that keep those electronic records trustworthy.',
    sortOrder: 160,
  },
  {
    code: 'CSV',
    name: 'Computerized System Validation',
    description:
      'The documented evidence that a computerized system consistently performs as intended for its regulated use, established before the system is relied upon.',
    sortOrder: 170,
  },
  {
    code: 'AUDIT_TRAILS_ACCESS',
    name: 'Audit Trails & Access Control',
    description:
      'The system-generated, time-stamped record of who changed what and when in an electronic system, and the user-access controls that prevent unauthorized or untraceable changes.',
    sortOrder: 180,
  },
  {
    code: 'VENDOR_OVERSIGHT',
    name: 'Vendor / Third-Party / SaaS Oversight',
    description:
      'The sponsor’s or CRO’s ongoing oversight of external vendors and hosted (SaaS) systems that create, process, or store trial data on its behalf.',
    sortOrder: 190,
  },
  {
    code: 'RECORD_RETENTION',
    name: 'Record Retention / Archiving',
    description:
      'The practices that keep trial records accessible, legible, and intact for the full period required by applicable regulation and the trial’s own records-retention agreements.',
    sortOrder: 200,
  },
  {
    code: 'TRAINING_QUALIFICATION',
    name: 'Training / Qualification',
    description:
      'The documented evidence that trial personnel hold the education, training, and experience needed for their trial responsibilities, kept current as the protocol or role changes.',
    sortOrder: 210,
  },
  {
    code: 'QUALITY_ASSURANCE_CAPA',
    name: 'Quality Assurance, Auditing & CAPA',
    description:
      'Independent review of trial-related activities to confirm compliance, and the corrective-and-preventive-action process that addresses findings from that review.',
    sortOrder: 220,
  },
  {
    code: 'INSPECTION_READINESS',
    name: 'Inspection Readiness',
    description:
      'The ongoing practices that keep a site, sponsor, or vendor prepared to demonstrate trial compliance and data integrity during a regulatory inspection at any time.',
    sortOrder: 230,
  },
  {
    code: 'DOCUMENTATION_PRACTICES',
    name: 'Good Documentation Practices',
    description:
      'The habits that keep any trial record - paper or electronic - clear, contemporaneous, correctable without obscuring the original entry, and properly attributed.',
    sortOrder: 240,
  },
  {
    code: 'PRIVACY_CONFIDENTIALITY',
    name: 'Privacy / Confidentiality',
    description:
      'The protection of subject identity and personal health information throughout collection, storage, transfer, and eventual de-identification or destruction.',
    sortOrder: 250,
  },
];

/** Gate 14 §11: a curated reference view, not a permission system. Each row
 * documents why the pairing is typical, grounded in standard GCP role
 * definitions - never implying exclusive ownership. */
const ROLE_DOMAIN_MAP: { domainCode: string; roleCode: string; rationale: string }[] = [
  {
    domainCode: 'INVESTIGATOR_RESPONSIBILITIES',
    roleCode: 'PRINCIPAL_INVESTIGATOR',
    rationale: 'Core PI accountability.',
  },
  {
    domainCode: 'INVESTIGATOR_RESPONSIBILITIES',
    roleCode: 'SUB_INVESTIGATOR',
    rationale: 'Delegated PI duties.',
  },
  {
    domainCode: 'PROTOCOL_COMPLIANCE',
    roleCode: 'PRINCIPAL_INVESTIGATOR',
    rationale: 'PI owns protocol adherence at site.',
  },
  {
    domainCode: 'PROTOCOL_COMPLIANCE',
    roleCode: 'CRA',
    rationale: 'CRA monitors and verifies protocol compliance.',
  },
  {
    domainCode: 'INFORMED_CONSENT',
    roleCode: 'PRINCIPAL_INVESTIGATOR',
    rationale: 'PI/delegate obtains consent.',
  },
  {
    domainCode: 'INFORMED_CONSENT',
    roleCode: 'CRC',
    rationale: 'CRC frequently administers the consent process.',
  },
  {
    domainCode: 'ETHICS_OVERSIGHT',
    roleCode: 'REGULATORY',
    rationale: 'Regulatory professionals manage EC/IRB submissions.',
  },
  {
    domainCode: 'ETHICS_OVERSIGHT',
    roleCode: 'PRINCIPAL_INVESTIGATOR',
    rationale: 'PI submits and responds to EC/IRB.',
  },
  {
    domainCode: 'SUBJECT_SAFETY',
    roleCode: 'PHARMACOVIGILANCE',
    rationale: 'Core safety-reporting function.',
  },
  {
    domainCode: 'SUBJECT_SAFETY',
    roleCode: 'PRINCIPAL_INVESTIGATOR',
    rationale: 'PI assesses and reports AEs/SAEs at site.',
  },
  {
    domainCode: 'SUBJECT_SAFETY',
    roleCode: 'CRC',
    rationale: 'CRC identifies and documents AEs during visits.',
  },
  {
    domainCode: 'SOURCE_DOCUMENTATION',
    roleCode: 'CRC',
    rationale: 'CRC generates and maintains source records.',
  },
  {
    domainCode: 'SOURCE_DOCUMENTATION',
    roleCode: 'CRA',
    rationale: 'CRA performs source-data verification.',
  },
  {
    domainCode: 'ESSENTIAL_DOCUMENTS',
    roleCode: 'CRA',
    rationale: 'CRA maintains/reviews the ISF and TMF.',
  },
  {
    domainCode: 'ESSENTIAL_DOCUMENTS',
    roleCode: 'SPONSOR',
    rationale: 'Sponsor owns the master TMF.',
  },
  {
    domainCode: 'MONITORING_QUALITY',
    roleCode: 'CRA',
    rationale: 'Monitoring is the CRA’s core function.',
  },
  {
    domainCode: 'MONITORING_QUALITY',
    roleCode: 'SPONSOR',
    rationale: 'Sponsor designs the risk-based monitoring plan.',
  },
  {
    domainCode: 'DATA_INTEGRITY',
    roleCode: 'QA',
    rationale: 'QA independently reviews data-integrity controls.',
  },
  {
    domainCode: 'DATA_INTEGRITY',
    roleCode: 'CLINICAL_OPERATIONS',
    rationale: 'Clinical operations owns day-to-day data quality.',
  },
  {
    domainCode: 'CLINICAL_DATA_MANAGEMENT',
    roleCode: 'CLINICAL_OPERATIONS',
    rationale: 'Data management is a clinical-operations function.',
  },
  {
    domainCode: 'BIOANALYTICAL_OPERATIONS',
    roleCode: 'PHARMACEUTICAL',
    rationale: 'Laboratory/bioanalytical work sits within pharmaceutical operations.',
  },
  {
    domainCode: 'BIOANALYTICAL_OPERATIONS',
    roleCode: 'QA',
    rationale: 'QA reviews bioanalytical batch records and audit trails.',
  },
  {
    domainCode: 'INVESTIGATIONAL_PRODUCT',
    roleCode: 'PRINCIPAL_INVESTIGATOR',
    rationale: 'PI is accountable for IP at site.',
  },
  {
    domainCode: 'INVESTIGATIONAL_PRODUCT',
    roleCode: 'SPONSOR',
    rationale: 'Sponsor manages IP supply/randomization.',
  },
  {
    domainCode: 'COMPUTERIZED_SYSTEMS',
    roleCode: 'CLINICAL_OPERATIONS',
    rationale: 'Clinical operations administers EDC/eCOA use.',
  },
  {
    domainCode: 'COMPUTERIZED_SYSTEMS',
    roleCode: 'QA',
    rationale: 'QA reviews electronic-record controls.',
  },
  {
    domainCode: 'CSV',
    roleCode: 'QA',
    rationale: 'QA reviews validation evidence before system reliance.',
  },
  {
    domainCode: 'AUDIT_TRAILS_ACCESS',
    roleCode: 'QA',
    rationale: 'QA reviews audit trails during record review.',
  },
  {
    domainCode: 'VENDOR_OVERSIGHT',
    roleCode: 'SPONSOR',
    rationale: 'Sponsor retains oversight of delegated vendors.',
  },
  {
    domainCode: 'VENDOR_OVERSIGHT',
    roleCode: 'CRO',
    rationale: 'CRO often manages day-to-day vendor interfaces.',
  },
  {
    domainCode: 'RECORD_RETENTION',
    roleCode: 'SPONSOR',
    rationale: 'Sponsor sets retention requirements/agreements.',
  },
  {
    domainCode: 'TRAINING_QUALIFICATION',
    roleCode: 'QA',
    rationale: 'QA verifies training records during audits.',
  },
  {
    domainCode: 'TRAINING_QUALIFICATION',
    roleCode: 'CRA',
    rationale: 'CRA verifies site-staff training/delegation logs.',
  },
  { domainCode: 'QUALITY_ASSURANCE_CAPA', roleCode: 'QA', rationale: 'Core QA/CAPA function.' },
  {
    domainCode: 'INSPECTION_READINESS',
    roleCode: 'QA',
    rationale: 'QA leads inspection-readiness activities.',
  },
  {
    domainCode: 'INSPECTION_READINESS',
    roleCode: 'REGULATORY',
    rationale: 'Regulatory professionals coordinate inspection response.',
  },
  {
    domainCode: 'DOCUMENTATION_PRACTICES',
    roleCode: 'CRC',
    rationale: 'CRC produces the majority of site documentation.',
  },
  {
    domainCode: 'PRIVACY_CONFIDENTIALITY',
    roleCode: 'PRINCIPAL_INVESTIGATOR',
    rationale: 'PI safeguards subject identity at site.',
  },
  {
    domainCode: 'GCP_FUNDAMENTALS',
    roleCode: 'OTHER',
    rationale: 'Applies to every clinical-research professional.',
  },
  {
    domainCode: 'SPONSOR_RESPONSIBILITIES',
    roleCode: 'SPONSOR',
    rationale: 'Direct sponsor accountability.',
  },
  { domainCode: 'CRO_OVERSIGHT', roleCode: 'CRO', rationale: 'Direct CRO accountability.' },
  {
    domainCode: 'CRO_OVERSIGHT',
    roleCode: 'SPONSOR',
    rationale: 'Sponsor retains ultimate responsibility despite delegation.',
  },
];

interface ObjectiveSeed {
  code: string;
  title: string;
  description: string;
  domainCode: string;
  topic?: string;
  roleCodesApplicable?: string[];
  rationale: string;
}

/** Gate 14 §13/§15/§16: every objective describes an observable learner
 * action (identify/assess/determine/verify/etc.), is tied to a domain, and
 * carries an explicit source basis - never a vague "understand X"
 * statement, never presented as an FDA/ICH requirement itself. */
const OBJECTIVES: ObjectiveSeed[] = [
  {
    code: 'LO-FUND-001',
    title: 'Identify the core GCP principles',
    description:
      'Identify the core ICH GCP principles (subject rights/safety/wellbeing, scientific soundness, informed consent, IRB/IEC oversight) in a described trial scenario.',
    domainCode: 'GCP_FUNDAMENTALS',
    rationale: 'Foundational curriculum requirement for every learner role.',
  },
  {
    code: 'LO-FUND-002',
    title: 'Distinguish GCP evidence from training interpretation',
    description:
      'Distinguish a documented regulatory finding, an expert practical observation, and a training interpretation of that observation when reading a case scenario.',
    domainCode: 'GCP_FUNDAMENTALS',
    rationale:
      'Directly supports the evidence-hierarchy safeguard this platform enforces (Gate 11-14).',
  },
  {
    code: 'LO-INV-001',
    title: 'Determine when an investigator must escalate a site issue',
    description:
      'Determine, given a described site issue, whether it requires investigator escalation to the sponsor, IRB/IEC, or both, and within what expected timeframe.',
    domainCode: 'INVESTIGATOR_RESPONSIBILITIES',
    roleCodesApplicable: ['PRINCIPAL_INVESTIGATOR', 'SUB_INVESTIGATOR'],
    rationale: 'Observation evidence (Warning Letters) repeatedly shows escalation failures.',
  },
  {
    code: 'LO-INV-002',
    title: 'Evaluate adequacy of investigator delegation',
    description:
      'Evaluate whether a delegation-of-duties log adequately documents who performed a given trial task and whether they were qualified to perform it.',
    domainCode: 'INVESTIGATOR_RESPONSIBILITIES',
    roleCodesApplicable: ['PRINCIPAL_INVESTIGATOR', 'CRA'],
    rationale: 'Reflects recurring practical-observation theme of delegation-log gaps.',
  },
  {
    code: 'LO-SPON-001',
    title: 'Assess sponsor oversight of a multi-site trial',
    description:
      'Assess whether a sponsor’s described oversight activities (monitoring cadence, safety review, vendor management) are proportionate to a trial’s risk profile.',
    domainCode: 'SPONSOR_RESPONSIBILITIES',
    roleCodesApplicable: ['SPONSOR'],
    rationale: 'Core sponsor-responsibility curriculum need.',
  },
  {
    code: 'LO-CRO-001',
    title: 'Determine whether sponsor oversight of a CRO is sufficient',
    description:
      'Given a described CRO delegation arrangement, determine whether the sponsor retained adequate oversight, and identify what evidence would demonstrate that oversight.',
    domainCode: 'CRO_OVERSIGHT',
    roleCodesApplicable: ['SPONSOR', 'CRO'],
    rationale:
      'Directly grounded in FDA Warning Letter evidence on sponsor-CRO oversight failures.',
  },
  {
    code: 'LO-PROTO-001',
    title: 'Classify a protocol deviation',
    description:
      'Classify a described protocol deviation by type (eligibility, procedural, safety-related) and determine whether it requires IRB/IEC notification.',
    domainCode: 'PROTOCOL_COMPLIANCE',
    roleCodesApplicable: ['CRA', 'PRINCIPAL_INVESTIGATOR'],
    rationale: 'Highest-volume real observation theme (protocol/eligibility deviations).',
  },
  {
    code: 'LO-PROTO-002',
    title: 'Verify eligibility-criteria compliance',
    description:
      'Verify, from a subject’s source documentation, whether enrollment eligibility criteria were met at the time of enrollment.',
    domainCode: 'PROTOCOL_COMPLIANCE',
    roleCodesApplicable: ['CRA', 'CRC'],
    rationale: 'Grounded in FDA Warning Letter eligibility-violation evidence.',
  },
  {
    code: 'LO-CONSENT-001',
    title: 'Verify legally effective informed consent',
    description:
      'Verify that a described informed-consent process (timing, version used, signatures, re-consent) meets the elements of legally effective informed consent.',
    domainCode: 'INFORMED_CONSENT',
    roleCodesApplicable: ['PRINCIPAL_INVESTIGATOR', 'CRC'],
    rationale: 'Grounded in recurring FDA Warning Letter informed-consent findings.',
  },
  {
    code: 'LO-CONSENT-002',
    title: 'Determine when re-consent is required',
    description:
      'Determine, given a described protocol amendment or new safety information, whether previously-enrolled subjects must be re-consented.',
    domainCode: 'INFORMED_CONSENT',
    roleCodesApplicable: ['PRINCIPAL_INVESTIGATOR', 'CRC'],
    rationale: 'Standard GCP curriculum requirement.',
  },
  {
    code: 'LO-ETHICS-001',
    title: 'Verify current IRB/IEC approval before a trial activity',
    description:
      'Verify, from site records, that an IRB/IEC approval was current and covered the specific protocol version in effect at the time of a described trial activity.',
    domainCode: 'ETHICS_OVERSIGHT',
    roleCodesApplicable: ['REGULATORY', 'PRINCIPAL_INVESTIGATOR'],
    rationale: 'Reflects real observation evidence of expired-approval gaps.',
  },
  {
    code: 'LO-SAFETY-001',
    title: 'Assess AE/SAE causality and reporting timeline',
    description:
      'Assess whether a described adverse event was appropriately graded, causality-assessed, and reported within the applicable expedited timeline.',
    domainCode: 'SUBJECT_SAFETY',
    roleCodesApplicable: ['PHARMACOVIGILANCE', 'PRINCIPAL_INVESTIGATOR'],
    rationale: 'Core safety-reporting curriculum need.',
  },
  {
    code: 'LO-SAFETY-002',
    title: 'Identify under-reporting of adverse events',
    description:
      'Identify indicators in source documentation that an adverse event may have occurred but was not captured in the case report form.',
    domainCode: 'SUBJECT_SAFETY',
    roleCodesApplicable: ['CRA', 'CRC'],
    rationale: 'Grounded in practical-observation evidence of AE documentation gaps.',
  },
  {
    code: 'LO-SRC-001',
    title: 'Verify source-data attributability and traceability',
    description:
      'Verify that an entry in a case report form can be traced back to a specific, attributable, contemporaneous source document.',
    domainCode: 'SOURCE_DOCUMENTATION',
    roleCodesApplicable: ['CRA'],
    rationale: 'Highest-density real practical-observation theme (source-document discrepancies).',
  },
  {
    code: 'LO-SRC-002',
    title: 'Identify an improper source-document correction',
    description:
      'Identify whether a correction to a source document followed good documentation practice (single-line-through, dated, initialed, reason given) or improperly obscured the original entry.',
    domainCode: 'SOURCE_DOCUMENTATION',
    roleCodesApplicable: ['CRA', 'QA'],
    rationale: 'Grounded in recurring bioanalytical/audit observation evidence.',
  },
  {
    code: 'LO-ESSDOC-001',
    title: 'Determine completeness of the Investigator Site File',
    description:
      'Determine, from an ISF index, which essential documents are missing, expired, or contain internal date/version inconsistencies.',
    domainCode: 'ESSENTIAL_DOCUMENTS',
    roleCodesApplicable: ['CRA'],
    rationale: 'Grounded in the highest-frequency real observation theme (TMF/ISF gaps).',
  },
  {
    code: 'LO-MON-001',
    title: 'Prioritize monitoring findings by risk',
    description:
      'Prioritize a list of described monitoring findings by their relative risk to subject safety and data reliability, using a risk-based quality management lens.',
    domainCode: 'MONITORING_QUALITY',
    roleCodesApplicable: ['CRA', 'SPONSOR'],
    rationale: 'Standard risk-based monitoring curriculum requirement.',
  },
  {
    code: 'LO-DI-001',
    title: 'Assess a dataset against ALCOA+ principles',
    description:
      'Assess whether a described dataset or record satisfies each ALCOA+ attribute, and identify which attribute is violated when it does not.',
    domainCode: 'DATA_INTEGRITY',
    roleCodesApplicable: ['QA', 'CLINICAL_OPERATIONS'],
    rationale: 'Directly grounded in FDA Warning Letter and audit data-integrity findings.',
  },
  {
    code: 'LO-DI-002',
    title: 'Identify a data-integrity red flag in raw data',
    description:
      'Identify indicators in raw laboratory or clinical data (backdating, unexplained corrections, missing entries) that suggest a data-integrity concern requiring investigation.',
    domainCode: 'DATA_INTEGRITY',
    roleCodesApplicable: ['QA'],
    rationale: 'Grounded in bioanalytical and computerized-system observation evidence.',
  },
  {
    code: 'LO-CDM-001',
    title: 'Reconcile a CRF discrepancy against source',
    description:
      'Reconcile a discrepancy between an electronic case report form entry and the corresponding source document, and determine the correct resolution path.',
    domainCode: 'CLINICAL_DATA_MANAGEMENT',
    roleCodesApplicable: ['CLINICAL_OPERATIONS', 'CRA'],
    rationale: 'Grounded in recurring CRF/EDC discrepancy observation evidence.',
  },
  {
    code: 'LO-BIO-001',
    title: 'Evaluate a bioanalytical method-validation gap',
    description:
      'Evaluate whether a described bioanalytical method-validation package adequately supports the analytical procedure it accompanies.',
    domainCode: 'BIOANALYTICAL_OPERATIONS',
    roleCodesApplicable: ['PHARMACEUTICAL', 'QA'],
    rationale: 'Grounded in real bio-analytical observation evidence (method validation gaps).',
  },
  {
    code: 'LO-BIO-002',
    title: 'Verify instrument calibration and maintenance records',
    description:
      'Verify that an instrument’s calibration and maintenance records support the validity of results generated during a specific test run.',
    domainCode: 'BIOANALYTICAL_OPERATIONS',
    roleCodesApplicable: ['QA'],
    rationale: 'Grounded in real audit observation evidence (calibration logbook gaps).',
  },
  {
    code: 'LO-IP-001',
    title: 'Reconcile investigational product accountability',
    description:
      'Reconcile investigational product accountability records (receipt, dispensing, return, destruction) and identify an unexplained discrepancy.',
    domainCode: 'INVESTIGATIONAL_PRODUCT',
    roleCodesApplicable: ['CRA', 'PRINCIPAL_INVESTIGATOR'],
    rationale: 'Standard IP-management curriculum requirement.',
  },
  {
    code: 'LO-IP-002',
    title: 'Assess a blinding-integrity breach',
    description:
      'Assess whether a described system-access or procedural failure resulted in a breach of treatment blinding, and determine the appropriate corrective action.',
    domainCode: 'INVESTIGATIONAL_PRODUCT',
    roleCodesApplicable: ['SPONSOR', 'CRA'],
    rationale:
      'Directly grounded in FDA Warning Letter computerized-system blinding-breach evidence.',
  },
  {
    code: 'LO-CS-001',
    title: 'Evaluate electronic-record access controls',
    description:
      'Evaluate whether a described computerized system’s user-access configuration (roles, shared credentials, administrator rights) adequately protects electronic trial records.',
    domainCode: 'COMPUTERIZED_SYSTEMS',
    roleCodesApplicable: ['QA', 'CLINICAL_OPERATIONS'],
    rationale: 'Directly grounded in FDA Warning Letter computerized-systems evidence.',
  },
  {
    code: 'LO-CSV-001',
    title: 'Determine whether a system change requires re-validation',
    description:
      'Determine, given a described change to a computerized system (upgrade, configuration change, new module), whether it requires re-validation before continued use.',
    domainCode: 'CSV',
    roleCodesApplicable: ['QA'],
    rationale: 'Directly grounded in FDA Warning Letter CSV-gap evidence.',
  },
  {
    code: 'LO-AUDIT-001',
    title: 'Identify a missing or disabled audit trail',
    description:
      'Identify, from a system description, whether audit-trail functionality was present, enabled, and reviewed as part of routine record review.',
    domainCode: 'AUDIT_TRAILS_ACCESS',
    roleCodesApplicable: ['QA'],
    rationale: 'Directly grounded in FDA Warning Letter and audit observation evidence.',
  },
  {
    code: 'LO-VENDOR-001',
    title: 'Assess vendor-hosted system data controls',
    description:
      'Assess whether a sponsor’s contractual and technical controls over a vendor-hosted system adequately prevent unauthorized data deletion and preserve inspection access.',
    domainCode: 'VENDOR_OVERSIGHT',
    roleCodesApplicable: ['SPONSOR', 'CRO'],
    rationale: 'Directly grounded in the eCOA vendor-deletion FDA Warning Letter observation.',
  },
  {
    code: 'LO-RETAIN-001',
    title: 'Determine appropriate record-retention duration',
    description:
      'Determine, given a described trial record and its regulatory/contractual context, the retention period that applies and who is responsible for maintaining it.',
    domainCode: 'RECORD_RETENTION',
    roleCodesApplicable: ['SPONSOR', 'QA'],
    rationale: 'Grounded in real observation evidence of premature record loss.',
  },
  {
    code: 'LO-TRAIN-001',
    title: 'Verify personnel training currency',
    description:
      'Verify, from a personal training record, whether trial staff were trained on the current protocol version and applicable procedures before performing a described task.',
    domainCode: 'TRAINING_QUALIFICATION',
    roleCodesApplicable: ['QA', 'CRA'],
    rationale: 'High-frequency real audit observation theme (training-record gaps).',
  },
  {
    code: 'LO-QA-001',
    title: 'Determine an adequate CAPA for an audit finding',
    description:
      'Determine whether a proposed corrective and preventive action adequately addresses the root cause of a described audit finding, not merely its symptom.',
    domainCode: 'QUALITY_ASSURANCE_CAPA',
    roleCodesApplicable: ['QA'],
    rationale: 'Core QA/CAPA curriculum requirement, grounded in audit observation evidence.',
  },
  {
    code: 'LO-INSP-001',
    title: 'Evaluate inspection readiness of a trial site',
    description:
      'Evaluate whether a trial site’s essential documents, source records, and electronic-system controls would withstand a regulatory inspection without advance notice.',
    domainCode: 'INSPECTION_READINESS',
    roleCodesApplicable: ['QA', 'REGULATORY'],
    rationale: 'Synthesizes the full real observation dataset’s recurring themes.',
  },
  {
    code: 'LO-DOC-001',
    title: 'Apply good documentation practice to a correction',
    description:
      'Apply good documentation practice when correcting an erroneous entry in a paper or electronic trial record, without obscuring the original value.',
    domainCode: 'DOCUMENTATION_PRACTICES',
    roleCodesApplicable: ['CRC', 'QA'],
    rationale: 'Grounded in recurring practical-observation documentation-correction evidence.',
  },
  {
    code: 'LO-PRIV-001',
    title: 'Identify a subject-privacy exposure',
    description:
      'Identify whether a described data-handling practice risks exposing a subject’s identity or protected health information beyond what the consent authorized.',
    domainCode: 'PRIVACY_CONFIDENTIALITY',
    roleCodesApplicable: ['CRC', 'QA'],
    rationale:
      'Standard privacy-curriculum requirement; supports the de-identification safeguards in Gates 11-13.',
  },
];

async function upsertDomains(prisma: PrismaService): Promise<Map<string, string>> {
  const idByCode = new Map<string, string>();
  for (const d of DOMAINS) {
    const domain = await prisma.gcpDomain.upsert({
      where: { code: d.code },
      update: { name: d.name, description: d.description, sortOrder: d.sortOrder },
      create: { code: d.code, name: d.name, description: d.description, sortOrder: d.sortOrder },
    });
    idByCode.set(d.code, domain.id);
  }
  console.log(`Domains upserted: ${idByCode.size}`);
  return idByCode;
}

async function upsertRoleMap(
  prisma: PrismaService,
  domainIdByCode: Map<string, string>,
  actorId: string,
): Promise<number> {
  const roles = await prisma.professionalRole.findMany({ select: { id: true, code: true } });
  const roleIdByCode = new Map(roles.map((r) => [r.code, r.id]));
  let count = 0;
  for (const entry of ROLE_DOMAIN_MAP) {
    const domainId = domainIdByCode.get(entry.domainCode);
    const professionalRoleId = roleIdByCode.get(entry.roleCode);
    if (!domainId || !professionalRoleId) {
      console.warn(
        `Skipping role-map entry: unknown domain/role (${entry.domainCode}/${entry.roleCode})`,
      );
      continue;
    }
    await prisma.gcpDomainRoleMap.upsert({
      where: { domainId_professionalRoleId: { domainId, professionalRoleId } },
      update: { rationale: entry.rationale },
      create: { domainId, professionalRoleId, rationale: entry.rationale, createdById: actorId },
    });
    count += 1;
  }
  console.log(`Role-map entries upserted: ${count}`);
  return count;
}

async function upsertObjectives(
  prisma: PrismaService,
  domainIdByCode: Map<string, string>,
  actorId: string,
): Promise<number> {
  const roles = await prisma.professionalRole.findMany({ select: { id: true, code: true } });
  const roleIdByCode = new Map(roles.map((r) => [r.code, r.id]));
  let count = 0;
  for (const o of OBJECTIVES) {
    const domainId = domainIdByCode.get(o.domainCode);
    if (!domainId) {
      console.warn(`Skipping objective ${o.code}: unknown domain ${o.domainCode}`);
      continue;
    }
    const roleIds = (o.roleCodesApplicable ?? [])
      .map((code) => roleIdByCode.get(code))
      .filter((id): id is string => Boolean(id));

    const existing = await prisma.learningObjective.findUnique({ where: { code: o.code } });
    if (existing) {
      await prisma.learningObjective.update({
        where: { id: existing.id },
        data: {
          title: o.title,
          description: o.description,
          domainId,
          rationale: o.rationale,
          ...(o.topic !== undefined ? { topic: o.topic } : {}),
        },
      });
      await prisma.learningObjectiveProfessionalRole.deleteMany({
        where: { learningObjectiveId: existing.id },
      });
      if (roleIds.length > 0) {
        await prisma.learningObjectiveProfessionalRole.createMany({
          data: roleIds.map((professionalRoleId) => ({
            learningObjectiveId: existing.id,
            professionalRoleId,
          })),
        });
      }
    } else {
      await prisma.learningObjective.create({
        data: {
          code: o.code,
          title: o.title,
          description: o.description,
          domainId,
          ...(o.topic !== undefined ? { topic: o.topic } : {}),
          sourceBasis: LearningObjectiveSourceBasis.EXPERT_CURATED_TRAINING_REQUIREMENT,
          rationale: o.rationale,
          createdById: actorId,
          ...(roleIds.length > 0
            ? {
                professionalRoles: {
                  createMany: {
                    data: roleIds.map((professionalRoleId) => ({ professionalRoleId })),
                  },
                },
              }
            : {}),
        },
      });
    }
    count += 1;
  }
  console.log(`Learning objectives upserted: ${count}`);
  return count;
}

async function main(): Promise<void> {
  const app = await NestFactory.createApplicationContext(AppModule, { logger: ['error', 'warn'] });
  try {
    const prisma = app.get(PrismaService);
    const admin = await prisma.user.findUnique({ where: { email: IMPORT_ADMIN_EMAIL } });
    if (!admin) {
      throw new Error(
        `Import admin account not found (${IMPORT_ADMIN_EMAIL}). Run observations:import first, or create an ${UserRole.ADMIN} user.`,
      );
    }

    const domainIdByCode = await upsertDomains(prisma);
    await upsertRoleMap(prisma, domainIdByCode, admin.id);
    await upsertObjectives(prisma, domainIdByCode, admin.id);

    console.log('\nGate 14 taxonomy seed complete.');
  } finally {
    await app.close();
  }
}

main().catch((error: unknown) => {
  console.error('Taxonomy seed failed:', error);
  process.exitCode = 1;
});
